/*
 * JSP generated by Resin-3.1.12 (built Mon, 29 Aug 2011 03:22:08 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _index__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write('	');
      uk.ac.dundee.computing.aec.ErrorMessageBean errorBean;
      synchronized (pageContext.getSession()) {
        errorBean = (uk.ac.dundee.computing.aec.ErrorMessageBean) pageContext.getSession().getAttribute("errorBean");
        if (errorBean == null) {
          errorBean = new uk.ac.dundee.computing.aec.ErrorMessageBean();
          pageContext.getSession().setAttribute("errorBean", errorBean);
        }
      }
      out.write(_jsp_string0, 0, _jsp_string0.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7170261747151080670L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("index.jsp"), 627244072721618388L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" />\r\n\r\n<title>Gossip</title>\r\n</head>\r\n\r\n<body>\r\n    <div id=\"page\">\r\n		\r\n        <div id=\"header\">\r\n        	<h1>Gossip </h1>\r\n            <h2>The first Gossip in dundee is here!</h2>\r\n            \r\n      </div>\r\n        <div id=\"bar\">\r\n            <ul>\r\n                <li><a href=\"register.jsp\">Register</a></li>\r\n                \r\n\r\n            </ul>\r\n      </div>\r\n	  <div class=\"contentTitle\"><h1>Gossing news</h1></div>\r\n        <div class=\"contentText\">\r\n          <p>This site is created for you to spread to the world the real gossip ;) </p>\r\n        \r\n        </div>\r\n		<div> <h1> Log In</h1></div>\r\n		\r\n		<form action=\"login\" method=\"post\">\r\n		<table>\r\n		<tr><td>Login: </td>   <td> <input type=\"text\" name=\"Email\"></td></tr>\r\n		<tr><td>Password: </td>   <td><input type=\"password\" name=\"password\"></td> </tr>\r\n		<tr><td><input type=submit value=\"Login\"></td>   </tr>\r\n		</table>\r\n		</form>\r\n		\r\n		<div> <a href =\"register.jsp\"> <h1> Sing up now </h1> </a> </div>\r\n		\r\n        \r\n    \r\n    \r\n       \r\n</div>\r\n</body>\r\n</html>\r\n".toCharArray();
  }
}
